name: chm

on:
  push:
    branches: 
      - master
      - develop
    paths-ignore:
      - 'doc/**'
      - 'Version3/**'
      - 'README.md'
  pull_request:
    branches: 
      - master
      - develop
    paths-ignore:
      - 'doc/**'
      - 'Version3/**'
      - 'README.md'
  schedule:
    - cron: '1 2 2/7 * *'
  workflow_dispatch:

jobs:
  build-chm:
    runs-on: windows-latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v4
